In [2]:
# import libraries

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import xgboost as xgb
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [3]:
df_rate = pd.read_excel("標準普爾最新信用評級.xls", header=7)
dict_rate = dict(zip(df_rate['Exchange:Ticker'], df_rate['S&P Entity Credit Rating - Issuer Credit Rating - Local Currency LT [Latest] (Rating)']))
feature_names = [col.replace('[', '').replace(']', '').replace('<', '') for col in pd.read_excel(f"NEW財務數據/財務數據/2019財務數據.xls", header=7).columns]

In [4]:
def data_processing(year):
    
    df = pd.read_excel(f"NEW財務數據/財務數據/{year}財務數據.xls", header=7)
    
    # replace columns as 2019 columns
    df.columns = feature_names
    
    # map Exchange:Ticker to credit rating
    df["rate"] = df["Exchange:Ticker"].map(dict_rate)

    # Drop the following columns
    df = df.drop(columns=["Company Name", "Security Tickers","Exchange:Ticker"])    

    # Create a rating map dictionary
    rating_map = {
        'AAA': 1, 'AA+': 1, 'AA': 1, 'AA-': 1, 'A+': 1, 'A': 1, 'A-': 1,
        'BBB+': 2, 'BBB': 2, 'BBB-': 2,
        'BB+': 3, 'BB': 3, 'BB-': 3,
        'B+': 4, 'B': 4, 'B-': 4, 'CCC+': 4, 'CCC': 4, 'CCC-': 4, 'D': 4,
        'NR': np.nan
    }

    # Map the credit rating values to numerical values 
    df['rate'] = df['rate'].map(lambda x: rating_map.get(x, x))
    
    # drop the nan in rate column
    df = df.dropna(subset=['rate'])

    # Replace '-' with NaN values in all columns
    for col in df.columns:
        df[col] = df[col].replace('-', np.nan)

    # Replace 'NM' with NaN values
    df = df.replace('NM', np.nan)

    # Fill NaN values with the mean
    for col in df.columns:
        
        df[col] = df[col].fillna(df[col].mean())
    
    df = df.dropna(axis=1, how='all')

    return df

In [5]:
df = pd.DataFrame()

for year in [2019,2020,2021,2022]:
    # Concatenate the DataFrames
    df = pd.concat([df, data_processing(year)], ignore_index=True)

In [6]:
df

Total Assets - Capital IQ Latest Annual - 5 ($USDmm, Historical rate)  \
0                                               36500.0                       
1                                                1524.7                       
2                                               67173.0                       
3                                               59352.0                       
4                                                2385.6                       
...                                                 ...                       
4179                                            93200.0                       
4180                                              398.6                       
4181                                            13900.0                       
4182                                             6852.9                       
4183                                             1077.7                       

      Total Capital - Capital IQ Latest Annual - 5 ($USDmm, Historical rate)  \
0                                          24593.000000                        
1                                           1113.500000                        
2                                          50288.000000                        
3                                          31864.000000                        
4                                           1515.400000                        
...                                                 ...                        
4179                                       17659.077567                        
4180                                         260.300000                        
4181                                       11333.000000                        
4182                                        3306.000000                        
4183                                         680.900000                        

      Sales/Sq. Ft., All (Net) - Capital IQ Latest Annual - 5 ($USD, Historical rate)  \
0                                               315.180                                 
1                                               315.180                                 
2                                               315.180                                 
3                                               315.180                                 
4                                               315.180                                 
...                                                 ...                                 
4179                                            419.175                                 
4180                                            419.175                                 
4181                                            419.175                                 
4182                                            419.175                                 
4183                                            419.175                                 

      Total Equity - Capital IQ Latest Annual - 5 ($USDmm, Historical rate)  \
0                                                9848.0                       
1                                                 936.3                       
2                                               30722.0                       
3                                               -8446.0                       
4                                                1218.6                       
...                                                 ...                       
4179                                             7463.0                       
4180                                              235.0                       
4181                                             4544.0                       
4182                                             1997.9                       
4183                                              126.4                       

      Total Enterprise Value My Setting Latest - 3 Year(s) ($USDmm, Historical

In [6]:
# 四種分類百分比

rate_counts  = df['rate'].value_counts()
rate_percentages = (rate_counts / rate_counts.sum()) * 100
rate_percentages

2.0    35.181644
3.0    30.401530
4.0    21.606119
1.0    12.810707
Name: rate, dtype: float64

In [7]:
le = LabelEncoder()

X = df.drop('rate', axis=1)
y = le.fit_transform(df['rate'])

# 對 X 資料標準化
scaler = StandardScaler().fit(X)
X = scaler.transform(X)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [8]:
# Create the XGBoost model
model = xgb.XGBClassifier(
    objective='binary:logistic',
    max_depth=3,
    learning_rate=0.1,
    n_estimators=1000,
    random_state=42
)

# Train the model
model.fit(X_train, y_train)

# Make predictions on the validation set
y_val_pred = model.predict(X_test)

# Calculate evaluation metrics
acc = accuracy_score(y_test, y_val_pred)                             # Calculate the accuracy score
f1 = f1_score(y_test, y_val_pred, average='weighted')                # Calculate the weighted F1-score
precision = precision_score(y_test, y_val_pred, average='weighted')  # Calculate the weighted precision
recall = recall_score(y_test, y_val_pred, average='weighted')        # Calculate the weighted recall
cm = confusion_matrix(y_test, y_val_pred)                            # Calculate the confusion matrix

# Print the evaluation metrics
print(f"Accuracy: {acc:.2f}")
print(f"F1-score: {f1:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print("Confusion Matrix:")
print(cm)

Accuracy: 0.91
F1-score: 0.91
Precision: 0.91
Recall: 0.91
Confusion Matrix:
[[ 94  12   3   0]
 [  2 265  14   1]
 [  0  15 236   6]
 [  0   1  24 164]]
