In [1]:
# import libraries

import pandas as pd
import numpy as np
import re
import os
import glob

import nltk
from nltk.stem import WordNetLemmatizer 

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
import xgboost as xgb

import torch
from transformers import AutoTokenizer, AutoModel

In [2]:
nltk.download("wordnet")

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\f8210\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [3]:
df_rate = pd.read_excel("標準普爾最新信用評級.xls", header=7)
dict_rate = dict(zip(df_rate['Exchange:Ticker'], df_rate['S&P Entity Credit Rating - Issuer Credit Rating - Local Currency LT [Latest] (Rating)']))
feature_names = [col.replace('[', '').replace(']', '').replace('<', '') for col in pd.read_excel(f"NEW財務數據/財務數據/2019財務數據.xls", header=7).columns]

In [4]:
def clean_text(text):
    
    # 去除 HTML 標籤
    text = re.sub(r'<[^>]+>', '', text)
    
    # 去除數字
    text = re.sub(r'\d+', '', text)
    
    # 去除標點符號
    text = re.sub(r'[^\w\s]', '', text)
    
    # 去除非英文單字
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    
    # 去除換行符號
    text = re.sub(r'\n', ' ', text)
    
    # 統一為小寫
    text = text.lower()
    
    # 詞性還原
    lemmatized_text = ' '.join([WordNetLemmatizer().lemmatize(w) for w in nltk.word_tokenize(text)])
    
    return lemmatized_text

In [5]:
def data_processing(year):
    
    df = pd.read_excel(f"NEW財務數據/財務數據/{year}財務數據.xls", header=7)
    
    # replace columns as 2019 columns
    df.columns = feature_names
    
    # map Exchange:Ticker to credit rating
    df["rate"] = df["Exchange:Ticker"].map(dict_rate)
    
    df['Exchange:Ticker'] = df['Exchange:Ticker'].str.split(':').str[-1]
    
    # For each ticker in the 'Exchange:Ticker' column, search for a matching text file
    for ticker in df['Exchange:Ticker']:
        txt_files = glob.glob(os.path.join(f'NEW文字檔/10-K文字檔/{year}txt/', f"{ticker}_*.txt"))
        if txt_files:
            with open(txt_files[0], 'r') as f:
                content = clean_text(f.read())
            df.loc[df['Exchange:Ticker'] == ticker, 'text'] = content
        else:
            df.loc[df['Exchange:Ticker'] == ticker, 'text'] = np.nan    

    # Drop the following columns
    df = df.drop(columns=["Company Name", "Security Tickers","Exchange:Ticker"])    

    # Create a rating map dictionary
    rating_map = {
        'AAA': 1, 'AA+': 1, 'AA': 1, 'AA-': 1, 'A+': 1, 'A': 1, 'A-': 1,
        'BBB+': 2, 'BBB': 2, 'BBB-': 2,
        'BB+': 3, 'BB': 3, 'BB-': 3,
        'B+': 4, 'B': 4, 'B-': 4, 'CCC+': 4, 'CCC': 4, 'CCC-': 4, 'D': 4,
        'NR': np.nan
    }

    # Map the credit rating values to numerical values 
    df['rate'] = df['rate'].map(lambda x: rating_map.get(x, x))
    
    # drop the nan in rate column
    df = df.dropna(subset=['rate'])

    # Replace '-' with NaN values in all columns
    for col in df.columns:
        df[col] = df[col].replace('-', np.nan)

    # Replace 'NM' with NaN values
    df = df.replace('NM', np.nan)

    # Fill NaN values with the mean
    for col in df.columns:
        if df[col].dtype != 'object':
            df[col] = df[col].fillna(df[col].mean())
    
    df = df.dropna(axis=1, how='all')
    df = df.dropna()

    return df

In [6]:
df = pd.DataFrame()

for year in [2019,2020,2021,2022]:
    # Concatenate the DataFrames
    df = pd.concat([df, data_processing(year)], ignore_index=True)

In [7]:
df

Total Assets - Capital IQ Latest Annual - 5 ($USDmm, Historical rate)  \
0                                               36500.0                       
1                                                1524.7                       
2                                               67173.0                       
3                                               59352.0                       
4                                                2385.6                       
...                                                 ...                       
3127                                             3770.3                       
3128                                            23456.4                       
3129                                              398.6                       
3130                                            13900.0                       
3131                                             6852.9                       

      Total Capital - Capital IQ Latest Annual - 5 ($USDmm, Historical rate)  \
0                                               24593.0                        
1                                                1113.5                        
2                                               50288.0                        
3                                               31864.0                        
4                                                1515.4                        
...                                                 ...                        
3127                                             3139.2                        
3128                                            19980.7                        
3129                                              260.3                        
3130                                            11333.0                        
3131                                             3306.0                        

      Sales/Sq. Ft., All (Net) - Capital IQ Latest Annual - 5 ($USD, Historical rate)  \
0                                               315.180                                 
1                                               315.180                                 
2                                               315.180                                 
3                                               315.180                                 
4                                               315.180                                 
...                                                 ...                                 
3127                                            419.175                                 
3128                                            419.175                                 
3129                                            419.175                                 
3130                                            419.175                                 
3131                                            419.175                                 

      Total Equity - Capital IQ Latest Annual - 5 ($USDmm, Historical rate)  \
0                                                9848.0                       
1                                                 936.3                       
2                                               30722.0                       
3                                               -8446.0                       
4                                                1218.6                       
...                                                 ...                       
3127                                             1967.7                       
3128                                            12666.4                       
3129                                              235.0                       
3130                                             4544.0                       
3131                                             1997.9                       

      Total Enterprise Value My Setting Latest - 3 Year(s) ($USDmm, Historical

In [8]:
# Sample 500 rows with a fixed random state
df = df.sample(n=500, random_state=42)
df = df.reset_index(drop=True)
df

Total Assets - Capital IQ Latest Annual - 5 ($USDmm, Historical rate)  \
0                                               1872.9                       
1                                             244718.0                       
2                                                412.7                       
3                                              10628.0                       
4                                                897.6                       
..                                                 ...                       
495                                            33975.7                       
496                                            10677.0                       
497                                            83850.4                       
498                                             7764.1                       
499                                             9131.9                       

     Total Capital - Capital IQ Latest Annual - 5 ($USDmm, Historical rate)  \
0                                               1679.8                        
1                                             176410.0                        
2                                                273.4                        
3                                               5306.0                        
4                                                674.7                        
..                                                 ...                        
495                                            23954.7                        
496                                             6989.0                        
497                                            23683.8                        
498                                             7028.2                        
499                                             7434.2                        

     Sales/Sq. Ft., All (Net) - Capital IQ Latest Annual - 5 ($USD, Historical rate)  \
0                                              372.425                                 
1                                              419.175                                 
2                                              315.180                                 
3                                              315.180                                 
4                                              344.200                                 
..                                                 ...                                 
495                                            344.200                                 
496                                            344.200                                 
497                                            419.175                                 
498                                            372.425                                 
499                                            419.175                                 

     Total Equity - Capital IQ Latest Annual - 5 ($USDmm, Historical rate)  \
0                                                603.6                       
1                                              65815.0                       
2                                                109.6                       
3                                              -1215.0                       
4                                                279.4                       
..                                                 ...                       
495                                             7582.2                       
496                                             5709.0                       
497                                             6648.8                       
498                                             4251.3                       
499                                             2887.1                       

     Total Enterprise Value My Setting Latest - 3 Year(s) ($USDmm, Historical rate)  \
0                                     

In [9]:
# 分成文本和數值型
df_numeric = df.drop("text", axis=1)
df_text = df[["text","rate"]]

# 純數值型

In [10]:
le = LabelEncoder()

X = df_numeric.drop('rate', axis=1)
y = le.fit_transform(df_numeric['rate'])

# 對 X 資料標準化
scaler = StandardScaler().fit(X)
X = scaler.transform(X)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [11]:
# 標準化後的數值
X_train

array([[-0.27905154, -0.25554753, -0.40128053, ...,  0.36127193,
        -0.42134266, -0.068453  ],
       [-0.37532667, -0.37851598,  0.32846992, ...,  0.35502765,
         0.01439546,  0.02229356],
       [-0.44889959, -0.50300362, -1.1515855 , ..., -0.05392202,
        -0.45246681, -0.07072834],
       ...,
       [-0.21795899, -0.17587146,  1.53717969, ...,  0.3639011 ,
         1.31624357, -0.12924076],
       [-0.39000712, -0.42894313, -1.1515855 , ...,  0.52838849,
        -0.42026941, -0.09381231],
       [-0.46491738, -0.52280282,  1.53717969, ...,  0.6102789 ,
        -0.72217368, -0.03691987]])

In [12]:
# Create the XGBoost model
model = xgb.XGBClassifier(
    objective='binary:logistic',
    max_depth=3,
    learning_rate=0.1,
    n_estimators=1000,
    random_state=42
)

# Train the model
model.fit(X_train, y_train)

# Make predictions on the validation set
y_test_pred = model.predict(X_test)

# Calculate evaluation metrics
acc = accuracy_score(y_test, y_test_pred)                             # Calculate the accuracy score
f1 = f1_score(y_test, y_test_pred, average='weighted')                # Calculate the weighted F1-score
precision = precision_score(y_test, y_test_pred, average='weighted')  # Calculate the weighted precision
recall = recall_score(y_test, y_test_pred, average='weighted')        # Calculate the weighted recall
cm = confusion_matrix(y_test, y_test_pred)                            # Calculate the confusion matrix

# Print the evaluation metrics
print(f"Accuracy: {acc:.2f}")
print(f"F1-score: {f1:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print("Confusion Matrix:")
print(cm)

Accuracy: 0.69
F1-score: 0.69
Precision: 0.72
Recall: 0.69
Confusion Matrix:
[[ 5  5  2  0]
 [ 6 30  8  0]
 [ 0  2 26  1]
 [ 0  0  7  8]]


# 純文本

In [13]:
# Split the DataFrame into training and test sets
df_train, df_test = train_test_split(df_text, test_size=0.2, random_state=42)

In [14]:
# Set the device
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Load the DistilBERT tokenizer and model
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")
model = AutoModel.from_pretrained("distilbert-base-uncased").to(device)

In [15]:
# Tokenize the text data for the training and validation sets
tokenized_train = tokenizer(df_train["text"].values.tolist(), padding=True, truncation=True, return_tensors="pt")
tokenized_test = tokenizer(df_test["text"].values.tolist(), padding=True, truncation=True, return_tensors="pt")

# Pass the tokenized text through the DistilBERT model to get the hidden states
with torch.no_grad():
    hidden_train = model(**tokenized_train)
    hidden_test = model(**tokenized_test)

# Get only the [CLS] token hidden states
cls_train = hidden_train.last_hidden_state[:,0,:]
cls_test = hidden_test.last_hidden_state[:,0,:]

In [16]:
# Encode the target variable
le = LabelEncoder()

# Concatenate the [CLS] token hidden states and the general features for the training set
x_train = cls_train
y_train = df_train["rate"]
y_train = le.fit_transform(y_train)

# Concatenate the [CLS] token hidden states and the general features for the validation set
x_test = cls_test
y_test = df_test["rate"]
y_test = le.fit_transform(y_test)

# Print the shapes of the input and target tensors
print(f"x_train shape: {x_train.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"x_test shape: {x_test.shape}")
print(f"y_test shape: {y_test.shape}")

x_train shape: torch.Size([400, 768])
y_train shape: (400,)
x_test shape: torch.Size([100, 768])
y_test shape: (100,)


In [17]:
# Create the XGBoost model
model = xgb.XGBClassifier(objective='multi:softprob',    # Set the objective function for multi-class classification
                            n_estimators=1000,           # Set the number of boosting iterations
                            max_depth=7,                 # Set the maximum depth of the decision trees
                            learning_rate=0.1,           # Set the learning rate for the boosting algorithm
                            random_state=42)             # Set the random state for reproducibility

# Train the model
model.fit(x_train, y_train)

# Make predictions on the validation set
y_test_pred = model.predict(x_test)

# Calculate evaluation metrics
acc = accuracy_score(y_test, y_test_pred)                             # Calculate the accuracy score
f1 = f1_score(y_test, y_test_pred, average='weighted')                # Calculate the weighted F1-score
precision = precision_score(y_test, y_test_pred, average='weighted')  # Calculate the weighted precision
recall = recall_score(y_test, y_test_pred, average='weighted')        # Calculate the weighted recall
cm = confusion_matrix(y_test, y_test_pred)                            # Calculate the confusion matrix

# Print the evaluation metrics
print(f"Accuracy: {acc:.2f}")
print(f"F1-score: {f1:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print("Confusion Matrix:")
print(cm)

Accuracy: 0.66
F1-score: 0.66
Precision: 0.67
Recall: 0.66
Confusion Matrix:
[[ 5  4  1  2]
 [ 0 33 10  1]
 [ 0  4 21  4]
 [ 1  3  4  7]]


# 數值 + 文本

In [18]:
# Encode the target variable
le = LabelEncoder()

# Concatenate the [CLS] token hidden states and the general features for the training set
x_train = torch.cat((cls_train, torch.from_numpy(X_train)), 1)
y_train = df_train["rate"]
y_train = le.fit_transform(y_train)

# Concatenate the [CLS] token hidden states and the general features for the validation set
x_test = torch.cat((cls_test, torch.from_numpy(X_test)), 1)
y_test = df_test["rate"]
y_test = le.fit_transform(y_test)

# Print the shapes of the input and target tensors
print(f"x_train shape: {x_train.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"x_test shape: {x_test.shape}")
print(f"y_test shape: {y_test.shape}")

x_train shape: torch.Size([400, 791])
y_train shape: (400,)
x_test shape: torch.Size([100, 791])
y_test shape: (100,)


In [19]:
# Create the XGBoost model
model = xgb.XGBClassifier(objective='multi:softprob',    # Set the objective function for multi-class classification
                            n_estimators=1000,           # Set the number of boosting iterations
                            max_depth=7,                 # Set the maximum depth of the decision trees
                            learning_rate=0.1,           # Set the learning rate for the boosting algorithm
                            random_state=42)             # Set the random state for reproducibility

# Train the model
model.fit(x_train, y_train)

# Make predictions on the validation set
y_test_pred = model.predict(x_test)

# Calculate evaluation metrics
acc = accuracy_score(y_test, y_test_pred)                             # Calculate the accuracy score
f1 = f1_score(y_test, y_test_pred, average='weighted')                # Calculate the weighted F1-score
precision = precision_score(y_test, y_test_pred, average='weighted')  # Calculate the weighted precision
recall = recall_score(y_test, y_test_pred, average='weighted')        # Calculate the weighted recall
cm = confusion_matrix(y_test, y_test_pred)                            # Calculate the confusion matrix

# Print the evaluation metrics
print(f"Accuracy: {acc:.2f}")
print(f"F1-score: {f1:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print("Confusion Matrix:")
print(cm)

Accuracy: 0.70
F1-score: 0.69
Precision: 0.69
Recall: 0.70
Confusion Matrix:
[[ 3  8  1  0]
 [ 5 32  7  0]
 [ 0  2 25  2]
 [ 0  1  4 10]]
